source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

platform :ios, '9.0'

target 'MyLearn' do

    # Masonry
    pod 'Masonry'
#    pod 'CocoaAsyncSocket'
#    pod 'YYCategories'
    pod 'AFNetworking'
#    pod 'GoogleWebRTC'
#pod 'AgoraMediaPlayer_iOS'

end
